
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author macbook
 */
public class Lab4b1 extends javax.swing.JFrame {

    /**
     * Creates new form Lab4b1
     */
    public Lab4b1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_Luong = new javax.swing.JTextField();
        btn_KiemTra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN");

        jLabel2.setText("HỌ VÀ TÊN");

        jLabel3.setText("NGÀY SINH");

        jLabel4.setText("LƯƠNG");

        btn_KiemTra.setText("KIỂM TRA");
        btn_KiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KiemTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_KiemTra)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txt_HoTen)
                        .addComponent(txt_NgaySinh)
                        .addComponent(txt_Luong, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_KiemTra)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_KiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KiemTraActionPerformed
        // TODO add your handling code here:
        String fullname=txt_HoTen.getText();
        String ngaysinh=txt_NgaySinh.getText();
        String luong=txt_Luong.getText();
        
       if(fullname.length()==0){
           JOptionPane.showMessageDialog(this,"Họ tên không được để trống!");
           txt_HoTen.setBackground(Color.red);
           txt_HoTen.requestFocus();
       }else{
           
           txt_HoTen.setBackground(Color.white);  
       }
        if(ngaysinh.length()==0){  
           JOptionPane.showMessageDialog(this,"Ngày sinh không được để trống!");
           txt_NgaySinh.setBackground(Color.red);
           txt_NgaySinh.requestFocus();
       }else{
            txt_NgaySinh.setBackground(Color.white); 
        }
        if(luong.length()==0) {  
           JOptionPane.showMessageDialog(this,"Lương không được để trống!");
           txt_Luong.setBackground(Color.red);
           txt_Luong.requestFocus();
       }else {
           JOptionPane.showMessageDialog(this,"Kiểm tra thành công!");
           txt_Luong.setBackground(Color.white);               
       }     
       try{
           double luongg=Double.parseDouble(luong);
       }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Lương phải là số:");
            txt_Luong.setBackground(Color.red);
            txt_Luong.requestFocus();
       }
       
       
        
//       try{
//           SimpleDateFormat formater = new SimpleDateFormat("dd-MM-yyyy");
//          Date ngay=formater.parse(ngaysinh);
//       }catch(Exception e){
//           JOptionPane.showMessageDialog(this,"Ngày sinh phải có định dạng dd-MM-yyyy");
//            txt_NgaySinh.setBackground(Color.red);
//            txt_NgaySinh.requestFocus();
//       }
        try{
            Date ngay=XDate.parse(ngaysinh,"dd-MM-yyyy");
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,"Ngày sinh phải có định dạng dd-MM-yyyy");
             txt_NgaySinh.setBackground(Color.YELLOW);
        }
           
    }//GEN-LAST:event_btn_KiemTraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab4b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab4b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab4b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab4b1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab4b1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KiemTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_Luong;
    private javax.swing.JTextField txt_NgaySinh;
    // End of variables declaration//GEN-END:variables
}
